<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<PropertyGroup>
		<DebugType>embedded</DebugType>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<RepositoryUrl>https://github.com/ArachisH/Eavesdrop</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<Title>Eavesdropper</Title>
		<Authors>ArachisH</Authors>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Description>HTTP(S) proxy server for Windows machines that allows for the interception, and modification of all HTTP/HTTPS traffic.</Description>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="System.Memory" Version="4.6.3" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All"/>
	</ItemGroup>

</Project>