name: Build

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Restore]
    types:
      - completed

jobs:
  on-success:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: dotnet build --no-restore --verbosity normal
