name: build

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      name: Git Checkout
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v3
      name: .NET Setup
      with:
        dotnet-version: 7.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '6.x'
        includePrerelease: true

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0

    - name: Restoring
      run: dotnet restore --verbosity normal

    - name: Building
      run: dotnet build --configuration Release --no-restore --verbosity normal

    - name: Testing
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal