name: build

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:

    - name: Git Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: .NET Setup
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.4.2
      with:
        versionSpec: '6.7.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v4.4.2

    - name: Restoring
      run: dotnet restore -v normal

    - name: Building
      run: dotnet build -c Release --no-restore -v normal

    - name: Testing (.NET 10)
      run: dotnet test -c Release --no-restore --no-build -v normal -f net10.0
