name: build

on:
  push:
    branches:
      - '**'
    tags:
      - '!**'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      name: Git Checkout
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v3
      id: dotnetstep
      name: .NET Setup
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0

    - name: Restoring
      run: dotnet restore --verbosity normal

    - name: Building
      run: dotnet build --configuration Release --no-restore --verbosity normal

    - name: Testing (.NET 5)
      run: dotnet test --configuration Release --no-restore --no-build -v n -f net5.0

    - name: Testing (.NET Core 2)
      run: dotnet test --configuration Release --no-restore --no-build -v n -f netcoreapp2.0