name: Build & Test < Self-Hosted >

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:

    - uses: actions/checkout@v3
      name: Git Checkout
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v3
      name: .NET Setup
      with:
        dotnet-version: 6.0.x

    - name: Restoring
      run: dotnet restore --verbosity normal

    - name: Building
      run: dotnet build --no-restore --verbosity normal

    - name: Testing
      run: dotnet test --no-restore --no-build --verbosity normal
