name: Restore
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  restore:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Restore
      run: dotnet restore --verbosity normal
