name: Test

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  on-success:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: dotnet test --no-build --verbosity normal
